export const enum ColorType { 
    Black,
    DarkBlue,
    DarkGreen,
    DarkAqua,
    DarkRed,
    DarkPurple,
    Gold,
    Gray,
    DarkGray,
    Blue,
    Green,
    Aqua,
    Red,
    LightPurple,
    Yellow,
    White,
    MinecoinGold
}

export const ColorTable = {
    [ColorType.Black]: "§0",
    [ColorType.DarkBlue]: "§1",
    [ColorType.DarkGreen]: "§2",
    [ColorType.DarkAqua]: "§3",
    [ColorType.DarkRed]: "§4",
    [ColorType.DarkPurple]: "§5",
    [ColorType.Gold]: "§6",
    [ColorType.Gray]: "§7",
    [ColorType.DarkGray]: "§8",
    [ColorType.Blue]: "§9",
    [ColorType.Green]: "§a",
    [ColorType.Aqua]: "§b",
    [ColorType.Red]: "§c",
    [ColorType.LightPurple]: "§d",
    [ColorType.Yellow]: "§e",
    [ColorType.White]: "§f",
    [ColorType.MinecoinGold]: "§g",
};