export const enum FormatCodeEnum { 
    Black,
    DarkBlue,
    DarkGreen,
    DarkAqua,
    DarkRed,
    DarkPurple,
    Gold,
    Gray,
    DarkGray,
    Blue,
    Green,
    Aqua,
    Red,
    LightPurple,
    Yellow,
    White,
    MinecoinGold,
    
    Obfuscated,
    Bold,
    Underline,
    Italic,
    Reset
}

export const FormatCodeTable = {
    [FormatCodeEnum.Black]: "§0",
    [FormatCodeEnum.DarkBlue]: "§1",
    [FormatCodeEnum.DarkGreen]: "§2",
    [FormatCodeEnum.DarkAqua]: "§3",
    [FormatCodeEnum.DarkRed]: "§4",
    [FormatCodeEnum.DarkPurple]: "§5",
    [FormatCodeEnum.Gold]: "§6",
    [FormatCodeEnum.Gray]: "§7",
    [FormatCodeEnum.DarkGray]: "§8",
    [FormatCodeEnum.Blue]: "§9",
    [FormatCodeEnum.Green]: "§a",
    [FormatCodeEnum.Aqua]: "§b",
    [FormatCodeEnum.Red]: "§c",
    [FormatCodeEnum.LightPurple]: "§d",
    [FormatCodeEnum.Yellow]: "§e",
    [FormatCodeEnum.White]: "§f",
    [FormatCodeEnum.MinecoinGold]: "§g",

    [FormatCodeEnum.Obfuscated]: "§k",
    [FormatCodeEnum.Bold]: "§l",
    [FormatCodeEnum.Underline]: "§n",
    [FormatCodeEnum.Italic]: "§o",
    [FormatCodeEnum.Reset]: "§r",
};